apiVersion: apps/v1
kind: Deployment
metadata:
  name: gk-frontend
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: gk-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gk-frontend
    spec:
      containers:
        - image: nikitagetman/gk-front:0.1
          imagePullPolicy: Always
          name: gk-frontend
          ports:
            - containerPort: 80
